cleaning config file,  adding non interrupting message event to wfc, and other fixes
philips-labs/workflow-capability pull request #40
Opened 2024-07-18 09:57 UTC by hopetes

This pull request contains the following: 
Cleaning config file for "pulse-physiology_FHIR" component, adding non interrupting boundary message event to WFC, checking when to complete task in fhir store and when to remove subscribed resource and handle error handling mechanism if no resource when getting data in getResource.
Compose file is added to build and run hapi-fhir, wfc, and camunda-engine at once.

2024-07-25 08:06 UTC, basbergevoet commented on docker-compose.yml
@hopetes I am not a Docker expert, but I see healtcheck statements that use the same port 8080 for both HAPI FHIR and Camunda engine. Is that correct?

2024-07-25 08:08 UTC, basbergevoet commented on engine/camunda/Dockerfile
@hopetes Why did you take out the comments? In general I like to see explanatory comments in a file......

2024-07-25 08:09 UTC, basbergevoet commented on engine/camunda/README.md
@hopetes In line 9 and 10, two different ways of running the created .jar file are given. Which one should I use? Why do you provide two different ways? It can only raise confusion.... Or is there a specific reason for it?

2024-07-25 08:18 UTC, basbergevoet commented on engine/camunda/src/main/java/org/camunda/bpm/delegate/InterfaceWfcHandler.java
@hopetes Not all parameters are explained for the handleBoundaryEvent method, and also description seems outdated...... Same for dataObjectReferenceImpl. Also, the parameters are mentioned, but none of them is explained......

Line 88: Why add a empty string to the messageName...... That wouldn't make sense. And if it does, then please explain in a comment why you do this.

Line 162: For me it is not directly clear with Unirest is and what it does. Perhaps worthwhile to write a short comment here.

2024-07-25 08:19 UTC, basbergevoet commented on workflow_capability_core/src/main/java/com/philips/healthsuite/workflowcapability/core/demos/FhirStoreInitialization.java
@hopetes Line 54: Why is this commented out, instead of deleted?????

2024-07-25 08:19 UTC, hopetes commented on docker-compose.yml
My bad, it was by mistake, it should be 8180.

2024-07-25 08:30 UTC, basbergevoet commented on workflow_capability_core/src/main/java/com/philips/healthsuite/workflowcapability/core/wfcservice/EngineQueryHandler.java
@hopetes Line 136: Why is the else clause doing a subscribe....? The subscribe is already done for the FETCH in the code above, right?

2024-07-25 08:31 UTC, hopetes commented on engine/camunda/Dockerfile
I didn't take out the comments, it is newly added compose file. But I agree I will add general comments.

2024-07-25 08:33 UTC, basbergevoet requested changes
@hopetes In general, many review remarks that were made you could have easily found yourself if you would have reviewed the files yourself...... It are repeated remarks from earlier pull request reviews...... Next time, please invest in reviewing yourself as well, before asking us to review.

2024-07-25 08:38 UTC, hopetes commented on workflow_capability_core/src/main/java/com/philips/healthsuite/workflowcapability/core/wfcservice/EngineQueryHandler.java
Based on the current implementation: 
GET -> just get data 
FETCH-> Get data if available if not Subscribe,
SUBSCRIBE-> just subscribe,
so, FETCH has if and else part to satisfy the requirement.

2024-07-25 08:57 UTC, basbergevoet commented on docker-compose.yml
@hopetes But then, how could it have worked????? Why didn't it fail with an error, or did tests fail????

2024-07-25 08:59 UTC, basbergevoet commented on engine/camunda/Dockerfile
@hopetes In my diff view below, I clearly see the lines with comments deleted (with a '-' in front, and colored red).

2024-07-25 09:01 UTC, basbergevoet commented on workflow_capability_core/src/main/java/com/philips/healthsuite/workflowcapability/core/wfcservice/EngineQueryHandler.java
@hopetes Then please make this very clear in the comments. And, by the way, 'SUBSCRIBE' is not a command that you can use in the query string, isn't it? Is it a default or something then?

2024-07-26 10:10 UTC, hopetes commented on engine/camunda/README.md
I get it. thank you I will remove it.

2024-07-26 10:13 UTC, hopetes commented on engine/camunda/src/main/java/org/camunda/bpm/delegate/InterfaceWfcHandler.java
I added the appropriate comments to each method and params, I also removed unwanted spaces, that was supposed to change to string but not applicable at this point, additionally I introduce code reuse by removing repeated parameters throughout class. 
(Parameter properties)

2024-07-26 10:14 UTC, hopetes commented on workflow_capability_core/src/main/java/com/philips/healthsuite/workflowcapability/core/demos/FhirStoreInitialization.java
you are right, It is not important to be there, so I removed it.

2024-07-26 10:17 UTC, hopetes commented on workflow_capability_core/src/main/java/com/philips/healthsuite/workflowcapability/core/wfcservice/EngineQueryHandler.java
Yes, it is not a command, it is a concept introduced to instruct the wfc to do subscription.

2024-07-26 10:23 UTC, hopetes commented on docker-compose.yml
If we clicked during running on docker to test if it's running, it should fail, technically we are clicking -> http://127.0.0.1:8080/fhir/metadata and this doesn't exist 

but internally it is running -> http://127.0.0.1:8180/fhir/metadata, so wfc for example cares on the actual port if it is running not on the testing, 

basically, it will not fail unless we click to check to test.

2024-07-26 10:27 UTC, hopetes commented on engine/camunda/Dockerfile
ohh, I was referring the newly added compose file, sorry I bring them back.

2024-07-26 11:46 UTC, basbergevoet commented on docker-compose.yml
@hopetes So, the lesson here is..... test the code. As we discussed yesterday, to start investing in testing.

2024-07-26 11:47 UTC, basbergevoet commented on engine/camunda/Dockerfile
@hopetes I don't see them back yet......

2024-07-26 11:54 UTC, basbergevoet approved these changes

2024-07-26 11:57 UTC, merged